# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sync.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsync.proto\x12\rjibon.sync.v1\"\xfd\x01\n\nReportItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x13\n\x0bsegment_key\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x14\n\x0cpayload_json\x18\x05 \x01(\t\x12\x1a\n\x12\x63reated_at_rfc3339\x18\x06 \x01(\t\x12\x1a\n\x12updated_at_rfc3339\x18\x07 \x01(\t\x12\x1f\n\x12\x64\x65leted_at_rfc3339\x18\x08 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0cis_tombstone\x18\t \x01(\x08H\x01\x88\x01\x01\x42\x15\n\x13_deleted_at_rfc3339B\x0f\n\r_is_tombstone\"\x90\x01\n\x10PushBatchRequest\x12\x12\n\ngateway_id\x18\x01 \x01(\t\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\t\x12\x19\n\x0cgateway_name\x18\x03 \x01(\tH\x00\x88\x01\x01\x12*\n\x07reports\x18\x04 \x03(\x0b\x32\x19.jibon.sync.v1.ReportItemB\x0f\n\r_gateway_name\"t\n\x11PushBatchResponse\x12\x19\n\x11idempotent_replay\x18\x01 \x01(\x08\x12\x14\n\x0crecord_count\x18\x02 \x01(\x05\x12\x15\n\rapplied_count\x18\x03 \x01(\x05\x12\x17\n\x0fsync_log_status\x18\x04 \x01(\t2\\\n\nSyncIngest\x12N\n\tPushBatch\x12\x1f.jibon.sync.v1.PushBatchRequest\x1a .jibon.sync.v1.PushBatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTITEM']._serialized_start=30
  _globals['_REPORTITEM']._serialized_end=283
  _globals['_PUSHBATCHREQUEST']._serialized_start=286
  _globals['_PUSHBATCHREQUEST']._serialized_end=430
  _globals['_PUSHBATCHRESPONSE']._serialized_start=432
  _globals['_PUSHBATCHRESPONSE']._serialized_end=548
  _globals['_SYNCINGEST']._serialized_start=550
  _globals['_SYNCINGEST']._serialized_end=642
# @@protoc_insertion_point(module_scope)
