# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sync_pb2 as sync__pb2


class SyncIngestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushBatch = channel.unary_unary(
                '/jibon.sync.v1.SyncIngest/PushBatch',
                request_serializer=sync__pb2.PushBatchRequest.SerializeToString,
                response_deserializer=sync__pb2.PushBatchResponse.FromString,
                _registered_method=True)


class SyncIngestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PushBatch,
                    request_deserializer=sync__pb2.PushBatchRequest.FromString,
                    response_serializer=sync__pb2.PushBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jibon.sync.v1.SyncIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jibon.sync.v1.SyncIngest', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncIngest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jibon.sync.v1.SyncIngest/PushBatch',
            sync__pb2.PushBatchRequest.SerializeToString,
            sync__pb2.PushBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
